### ISSUE TITLE
Issue 2: Add Comments to html file

### ISSUE THREAD

**Issue by NombuleloMudzwiri** [Nombulie/OnlineResume#4]
The codebase of the personal web page could benefit from improved readability and maintainability through the addition of comments. This issue involves reviewing the code and adding meaningful comments to explain the purpose of functions, variables, and sections.

**Comment by Nombulie** [comment]
comments were added to the html file to enhance readability

**Comment by NombuleloMudzwiri** [comment]
comments were added to the html file to enhance readability
